### ISSUE TITLE
Not working with vim-plug

### ISSUE THREAD

**Issue by basicBrogrammer** [joukevandermaas/vim-ember-hbs#7]
![image](https://user-images.githubusercontent.com/6913826/48175291-9ff88100-e2c8-11e8-9e78-04a1e482b0ee.png)

![image](https://user-images.githubusercontent.com/6913826/48175319-b6064180-e2c8-11e8-98d4-268c9de361e0.png)

**Comment by joukevandermaas** [comment]
I don't know what is 'vim-plug' and I've never used it. Could you explain what it's for and what we would need to do to support it?

**Comment by basicBrogrammer** [comment]
Sorry Its just a plugin manager like pathogen https://github.com/junegunn/vim-plug .... its weird even the https://vimawesome.com/plugin/vim-mustache-handlebars package wasn't highlighting :/ I can dig into it a little bit. I think the vim-emblem syntax highlighter works I'll double check

**Comment by basicBrogrammer** [comment]
Yup it does 🤔 
Wonder what the diff is https://github.com/yalesov/vim-emblem

**Comment by joukevandermaas** [comment]
Looks like they have a ftplugin directory where we don't, but I don't see why that should matter. Can  you try with *just* vim-ember-hbs, turning off all other plugins? If that still doesn't work it must be the integration. Otherwise it's likely some plugins interfering with each other.

**Comment by NullVoxPopuli** [comment]
vim-ember-hbs works with vim-plug as of the time of this comment. see https://github.com/NullVoxPopuli/coc-ember#minimum-config

**Comment by basicBrogrammer** [comment]
Its working i have to just open the hbs file then `:e` (reopen) it
